openapi: 3.0.0
info:
  title: Todo Chatbot API
  description: API for AI-powered todo chatbot functionality
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server

paths:
  /api/chat:
    post:
      summary: Send message to AI chatbot
      description: Process user message and return AI response with potential tool calls
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: User message to the chatbot
                  example: "Add a task to buy groceries"
                conversation_id:
                  type: integer
                  description: Optional existing conversation ID
                  example: 123
              required:
                - message
      responses:
        '200':
          description: Successful response from AI chatbot
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: AI-generated response
                    example: "I've added the task 'buy groceries' for you."
                  conversation_id:
                    type: integer
                    description: ID of the conversation (new or existing)
                    example: 123
                  tool_calls:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: Name of the tool called
                          example: "add_task"
                        arguments:
                          type: object
                          description: Arguments passed to the tool
                          example:
                            title: "buy groceries"
                            description: "Get milk, bread, and eggs"
                  message_id:
                    type: integer
                    description: ID of the message just sent
                    example: 456
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
      example:
        error: "Invalid request format"
        code: "BAD_REQUEST"