import type { Metadata } from "next";
import  localFont  from "next/font/local";
import "./globals.css";

// Load Geist Sans (regular) locally
const geistSans = localFont({
  src: "./public/fonts/Geist-Regular.woff2",
  variable: "--font-geist-sans",
  display: "swap",
});

// Load Geist Mono (monospaced) locally
const geistMono = localFont({
  src: "./public/fonts/GeistMono-Regular.woff2",
  variable: "--font-geist-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Hackathon Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
